pipeline {
agent any

environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')   // Jenkins credentials ID
    DOCKERHUB_USER = 'sarralabidi984'                                 // Your Docker Hub username
    IMAGE_NAME = 'cookapp-backend'                                      // Image name
    IMAGE_TAG = 'latest'
}

stages {

    stage('Checkout Code') {
        steps {
            echo '📥 Cloning repository...'
            checkout scm
        }
    }

    stage('Build with Maven') {
        steps {
            dir('Cookingapp-cookappbackend/Cookingapp-cookappbackend') {
                echo '🔧 Building Spring Boot app with Maven...'
                sh 'mvn clean package -DskipTests'
            }
        }
    }

    stage('Build Docker Image') {
    steps {
        dir('Cookingapp-cookappbackend/Cookingapp-cookappbackend') {
            echo '🐳 Building Docker image...'
            sh '''
                docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG .
            '''
        }
    }
}


    stage('Push to Docker Hub') {
        steps {
            echo '☁️ Pushing image to Docker Hub...'
            sh '''
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
            '''
        }
    }

  stage('Deploy to Kubernetes') {
            steps {
                echo '🚀 Deploying to Kubernetes...'
                withKubeConfig([credentialsId: 'kubeconfig']) {
                    sh '''
                        kubectl apply -f k8s/deployment.yaml
                        kubectl apply -f k8s/service.yaml
                    '''
                }
            }
        }
}

post {
    success {
        echo '✅ Pipeline completed successfully!'
    }
    failure {
        echo '❌ Pipeline failed. Check logs in Jenkins.'
    }
}


}
